name: wall_haven
description: "A cross-platform wallpaper application powered by Wallhaven API."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State management
  signals: ^6.3.0

  # Dependency injection
  get_it: ^9.2.0

  # Routing
  auto_route: ^9.2.2

  # Network
  http: ^1.2.0

  # Database
  # sqlite3: ^2.9.4
  laconic: ^1.0.0
  sqlite3_flutter_libs: ^0.5.41

  # Local storage
  shared_preferences: ^2.2.0

  # Image
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.2
  photo_view: ^0.15.0

  # Utilities
  uuid: ^4.5.1
  logger: ^2.6.2
  path_provider: ^2.1.3
  crypto: ^3.0.3
  permission_handler: ^11.3.1

  # Platform specific (save images to gallery)
  gal: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.0
  auto_route_generator: ^9.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - asset/
    - asset/font/
    - asset/image/

  fonts:
    - family: Exo
      fonts:
        - asset: asset/font/Exo-Thin.ttf
          weight: 100
        - asset: asset/font/Exo-ExtraLight.ttf
          weight: 200
        - asset: asset/font/Exo-Light.ttf
          weight: 300
        - asset: asset/font/Exo-Regular.ttf
          weight: 400
        - asset: asset/font/Exo-Medium.ttf
          weight: 500
        - asset: asset/font/Exo-SemiBold.ttf
          weight: 600
        - asset: asset/font/Exo-Bold.ttf
          weight: 700
        - asset: asset/font/Exo-ExtraBold.ttf
          weight: 800
        - asset: asset/font/Exo-Black.ttf
          weight: 900